description: >- This file specifies the base configuration for the prediction of in ICU mortality,
  leveraging only the first 48 hours of data after ICU admission, with a 24 hour gap between the input window
  and the target window. Patients who die or are discharged from the ICU in the gap window are excluded.
  Patients who die in the same hospital stay but in a subsequent ICU stay are **not** postiive labels for this
  task.
  Note that this task is in-**ICU** mortality, not in-**hospital** mortality or **30-day** mortality, which
  are different tasks.
  Note that this task is predicting the outcome for a patient's entire ICU admission, not just the first 48
  hours or the subsequent 48 hours after the trigger event. Imminent mortality (on various time-scales) are
  different tasks.

predicates:
  icu_admission_0:
    code: ICU_ADMISSION//Medical Intensive Care Unit (MICU)
  icu_admission_1:
    code: ICU_ADMISSION//Medical/Surgical Intensive Care Unit (MICU/SICU)
  icu_admission_2:
    code: ICU_ADMISSION//Cardiac Vascular Intensive Care Unit (CVICU)
  icu_admission_3:
    code: ICU_ADMISSION//Surgical Intensive Care Unit (SICU)
  icu_admission_4:
    code: ICU_ADMISSION//Trauma SICU (TSICU)
  icu_admission_5:
    code: ICU_ADMISSION//Coronary Care Unit (CCU)
  icu_admission_6:
    code: ICU_ADMISSION//Neuro Intermediate
  icu_admission_7:
    code: ICU_ADMISSION//Neuro Surgical Intensive Care Unit (Neuro SICU)
  icu_admission_8:
    code: ICU_ADMISSION//Neuro Stepdown
  icu_admission:
    or(icu_admission_0,icu_admission_1,icu_admission_2,icu_admission_3,icu_admission_4,icu_admission_5,icu_admission_6,icu_admission_7,icu_admission_8)

  icu_discharge_0:
    code: ICU_DISCHARGE//Medical Intensive Care Unit (MICU)
  icu_discharge_1:
    code: ICU_DISCHARGE//Medical/Surgical Intensive Care Unit (MICU/SICU)
  icu_discharge_2:
    code: ICU_DISCHARGE//Cardiac Vascular Intensive Care Unit (CVICU)
  icu_discharge_3:
    code: ICU_DISCHARGE//Surgical Intensive Care Unit (SICU)
  icu_discharge_4:
    code: ICU_DISCHARGE//Coronary Care Unit (CCU)
  icu_discharge_5:
    code: ICU_DISCHARGE//Trauma SICU (TSICU)
  icu_discharge_6:
    code: ICU_DISCHARGE//Neuro Intermediate
  icu_discharge_7:
    code: ICU_DISCHARGE//Neuro Stepdown
  icu_discharge_8:
    code: ICU_DISCHARGE//Neuro Surgical Intensive Care Unit (Neuro SICU)
  icu_discharge:
    or(icu_discharge_0,icu_discharge_1,icu_discharge_2,icu_discharge_3,icu_discharge_4,icu_discharge_5,icu_discharge_6,icu_discharge_7,icu_discharge_8)

  death:
    code: DEATH
  discharge_or_death:
    expr: or(icu_discharge, death)

trigger: icu_admission

windows:
  input:
    start: NULL
    end: trigger + 48h
    start_inclusive: True
    end_inclusive: True
  gap:
    start: input.end
    end: start + 24h
    start_inclusive: False
    end_inclusive: True
    has:
      icu_admission: (None, 0)
      icu_discharge: (None, 0)
      death: (None, 0)
  target:
    start: gap.end
    end: start -> discharge_or_death
    start_inclusive: False
    end_inclusive: True
    label: death
